[build]
builder = "DOCKER"

[deploy]
startCommand = "gunicorn -c gunicorn.conf.py WBC_Classification.wsgi:application"
port = 8080
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
