[build]
builder = "DOCKER"

[deploy]
startCommand = "python manage.py migrate && gunicorn -c gunicorn.conf.py WBC_Classification.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
